In [19]:
import pandas as pd

results_path = 'emo_search_aggregate_results.csv'

results_df = pd.read_csv(results_path)

In [20]:
results_df.columns

Index(['Portfolio_id', 'Emotion', 'Word', 'Sentence', 'Sentence_id',
       'Search_method', 'Validation_method'],
      dtype='str')

## Emotion frequency overall

The most frequent emotions were interest, struggle, and surprise. With my script, I did not find many expressions of happiness or annoyance.

In [21]:
results_df[['Emotion' ,'Word']].groupby(['Emotion']).count().sort_values(by='Word', ascending=False)

              Word
Emotion
interest        48
struggle        25
surprise        14
appreciation     8
annoyance        2
happiness        1

## Word frequency overall

The course participants seemed to find many things interesting. This might point to some limitations in vocabulary regarding expressing interest and fascination in different aspects. Also, 'interesting' can be a generalized word used when one is not sure, how else to describe a certain result in the moment. The second most common word is challenges: it's likely due to the nature of the course; the students often discuss 'challenges' of visualisations.

From my manual validation process, I can say the word 'value' was the biggest offender when it comes to the false positives: I decided to keep it in the search dictionary to hopefully catch an expression like 'In this course, I valued X and Y.', but most of the time it was just variable values. Here, the AI method would've been much more effective!

In [22]:
results_df[['Emotion' ,'Word']].groupby(['Word']).count().sort_values(by='Emotion', ascending=False)

              Emotion
Word
interesting        28
challenges         15
surprised           6
interested          5
interest            5
appreciate          4
challenge           4
curious             3
surprisingly        3
wonder              2
wondering           2
struggled           2
appreciation        2
annoyance           1
fascinating         1
engaging            1
engage              1
difficulty          1
difficulties        1
Curious             1
annoyed             1
appreciated         1
pleased             1
obstacle            1
intriguing          1
intrigued           1
interests           1
startling           1
struggles           1
value               1

## Overall number of emotional words found per portfolio

In [23]:
results_df[[ 'Portfolio_id', 'Word']].groupby('Portfolio_id').count().sort_values(by='Word', ascending=False)

              Word
Portfolio_id
8               19
1               12
12              12
2               10
6                8
3                6
9                6
4                6
10               5
7                5
14               4
5                3
11               1
13               1

## Emotion frequency per portfolio

In [13]:
results_df[[ 'Portfolio_id' , 'Emotion' ,'Word']].groupby(['Portfolio_id','Emotion']).count().sort_values(by=['Portfolio_id','Word'], ascending=True)

                           Word
Portfolio_id Emotion
1            interest         5
             struggle         7
2            interest         4
             struggle         6
3            interest         1
             struggle         1
             appreciation     2
             surprise         2
4            struggle         1
             surprise         1
             interest         4
5            surprise         1
             interest         2
6            appreciation     1
             struggle         2
             interest         5
7            appreciation     1
             interest         1
             surprise         1
             struggle         2
8            surprise         2
             interest        17
9            interest         1
             surprise         1
             struggle         4
10           annoyance        1
             interest         1
             struggle         1
             surprise         2
11           interest         1
12           annoyance        1
             happiness        1
             surprise         2
             appreciation     4
             interest         4
13           interest         1
14           interest         1
             struggle         1
             surprise         2